### ISSUE TITLE
Speed has trouble disabling, faulty

### ISSUE THREAD

**Issue by A9039** [OvermindMC/Infernus#1]
eh you know

**Comment by EchoHackCmd** [comment]
More information please

**Comment by A9039** [comment]
> More information please

when disabling, does not disable like intended _sometimes_, or does not work properly, and it's also just really not unstable, but not stable either, ex: it's not like any other speed in any other client. i would recommend redoing speed, or using a pointer, or it could just be a memory leak 💀

**Comment by EchoHackCmd** [comment]
I'll look into it soon

**Comment by baseds** [comment]
Don't think someone who copy pastes Horion should be giving programming advice

**Comment by cooperpfl** [comment]
LOL

**Comment by A9039** [comment]
> Don't think someone who copy pastes Horion should be giving programming advice

huh? my client is in c# stupid.

**Comment by baseds** [comment]
> > Don't think someone who copy pastes Horion should be giving programming advice
> 
> huh? my client is in c# stupid.

![Screenshot from 2020-11-11 15-02-23](https://user-images.githubusercontent.com/70320706/98827558-ed1b0a80-242e-11eb-940f-f240006df84b.png)
![Screenshot from 2020-11-11 15-03-07](https://user-images.githubusercontent.com/70320706/98827816-353a2d00-242f-11eb-90e5-077a39a5a3d9.png)

TFW ur in denial

**Comment by A9039** [comment]
> > > Don't think someone who copy pastes Horion should be giving programming advice
> > 
> > 
> > huh? my client is in c# stupid.
> 
> ![Screenshot from 2020-11-11 15-02-23](https://user-images.githubusercontent.com/70320706/98827558-ed1b0a80-242e-11eb-940f-f240006df84b.png)
> ![Screenshot from 2020-11-11 15-03-07](https://user-images.githubusercontent.com/70320706/98827816-353a2d00-242f-11eb-90e5-077a39a5a3d9.png)
> 
> TFW ur in denial

am i? with your logic, oldfag is a skid lmfao. just stop this shit fr it's pathetic, no one cares. my client is in c# so don't try to start shit again k ty have a great day.

**Comment by Hackerboi69420** [comment]
Hydrogen client!
https://discord.gg/5qDjwQv

**Comment by baseds** [comment]
> 
> 
> > > > Don't think someone who copy pastes Horion should be giving programming advice
> > > 
> > > 
> > > huh? my client is in c# stupid.
> > 
> > 
> > ![Screenshot from 2020-11-11 15-02-23](https://user-images.githubusercontent.com/70320706/98827558-ed1b0a80-242e-11eb-940f-f240006df84b.png)
> > ![Screenshot from 2020-11-11 15-03-07](https://user-images.githubusercontent.com/70320706/98827816-353a2d00-242f-11eb-90e5-077a39a5a3d9.png)
> > TFW ur in denial
> 
> am i? with your logic, oldfag is a skid lmfao. just stop this shit fr it's pathetic, no one cares. my client is in c# so don't try to start shit again k ty have a great day.

oldfag added stuff atleast, and who mentioned oldfag?
