### ISSUE TITLE
GUI issues when building from Source

### ISSUE THREAD

**Issue by RR3Dev** [OvermindMC/Infernus#2]
When I build it from the source code the GUI doesn't show

**Comment by ghost** [comment]
1) stop skid
2) build as x64 release
that should work

**Comment by RR3Dev** [comment]
> 1. stop skid
> 2. build as x64 release
>    that should work

Im not skidding, just wanted to see how it worked, also when i build it like that i get this: Severity	Code	Description	Project	File	Line	Suppression State
Error	C1047	The object or library file \Infernus\packages\minhook.1.3.3\build\native\..\..\lib\native\lib\libMinHook.lib' was created with an older compiler than other objects; rebuild old objects and libraries	Infernus	C:\Users\-\Documents\GitHub\Infernus\Infernus\LINK	1

**Comment by RR3Dev** [comment]
> > 1. stop skid
> > 2. build as x64 release
> >    that should work
> 
> Im not skidding, just wanted to see how it worked, also when i build it like that i get this: Severity Code Description Project File Line Suppression State
> Error C1047 The object or library file \Infernus\packages\minhook.1.3.3\build\native....\lib\native\lib\libMinHook.lib' was created with an older compiler than other objects; rebuild old objects and libraries Infernus C:\Users-\Documents\GitHub\Infernus\Infernus\LINK 1

I have a fix

**Comment by EchoHackCmd** [comment]
Go to Project > Manage Nuget Packages > Search : MinHook > Install

Once you've installed MinHook go to Infernus/Packages/minhook.1.3.3/lib/native/lib then rename libMinHook-x64-v141-mtd.lib to libMinHook.lib
